package edu.gtri.gpssample.constants

enum class Keys {
    kPin,
    kRole,
    kSSID,
    kPass,
    kPayload,
    kTeam_id,
    kEditMode,
    kUserName,
    kStudyName,
    kUser_uuid,
    kRule_uuid,
    kConfigName,
    kField_uuid,
    kStudy_uuid,
    kQuickStart,
    kFilter_uuid,
    kConfig_uuid,
    kSample_uuid,
    kEnumArea_id,
    kNavPlan_uuid,
    kSamplingMethod,
}