package edu.gtri.gpssample.utils

enum class NetworkConnectionStatus {
    UNKNOWN_STATUS, INITIALIZING, CONNECTING, CONNECTED, PAIRED, NOT_CONNECTED, NOT_PAIRED,
    PAIRED_NOT_AVAILABLE,
    WIFI_NOT_AVAILABLE, PARTIAL_CONNECTION, MISSING_PERMISSIONS
}